#!/usr/bin/env bash
docker run -it -v $ANDROID_HOME:/opt/android-sdk -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $XAUTHORITY:/home/ubuntu/.Xauthority --net=host -v /dev/kvm:/dev/kvm android-studio
