#!/usr/bin/env bash
docker run -it \
  --privileged
  -v $HOME/AndroidStudioProjects:/home/ubuntu/AndroidStudioProjects \
  -v $HOME/.android:/home/ubuntu/.android \
  -v $HOME/.AndroidStudioPreview2.0:/home/ubuntu/.AndroidStudioPreview2.0 \
  -v /dev/bus/usb:/dev/bus/usb \
  -v /dev/kvm:/dev/kvm \
  -v $ANDROID_HOME:/opt/android-sdk \
  -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v $XAUTHORITY:/home/ubuntu/.Xauthority \
  --net host \
  yongjhih/android-studio
